#!/usr/bin/env python3
"""Generate the wiring for the webmock brands from brands.json.

Single source of truth = brands.json. This writes the derived, committed
artifacts so the mock lab works out of the box, and can be re-run whenever you
add a brand:

  - ca/mock-domains.txt      → extra leaf-cert domains (ca/gen.sh reads it)
  - proxy/mocks.caddy        → one TLS reverse_proxy block per domain → webmock
  - sites/webmock/aliases.txt→ the docker DNS aliases to paste under the proxy
                               service in compose.net.yml (also printed)

Usage:  python3 sites/webmock/build.py      (run from the net-user-pl root)
Then:   bash ca/gen.sh && docker compose -f compose.net.yml up -d --build
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]           # net-user-pl/
BRANDS = json.loads((ROOT / "sites/webmock/brands.json").read_text())["brands"]
DOMAINS = [b["domain"] for b in BRANDS]
WEBMOCK_PORT = 9860


def write_ca_domains() -> None:
    (ROOT / "ca/mock-domains.txt").write_text(
        "# generated by sites/webmock/build.py — extra leaf-cert domains\n"
        + "\n".join(DOMAINS) + "\n")


def write_caddy() -> None:
    blocks = [("# generated by sites/webmock/build.py — do not edit by hand.\n"
               "# One TLS site block per mock brand; all proxy to the single webmock service.")]
    for d in DOMAINS:
        blocks.append(
            f"{d}, www.{d} {{\n"
            f"\ttls /certs/{d}.pem /certs/{d}.key\n"
            f"\treverse_proxy webmock:{WEBMOCK_PORT}\n"
            f"}}")
    (ROOT / "proxy/mocks.caddy").write_text("\n\n".join(blocks) + "\n")


def write_aliases() -> None:
    lines = []
    for d in DOMAINS:
        lines += [f"          - {d}", f"          - www.{d}"]
    (ROOT / "sites/webmock/aliases.txt").write_text("\n".join(lines) + "\n")
    return "\n".join(lines)


def main() -> int:
    write_ca_domains()
    write_caddy()
    aliases = write_aliases()
    print(f"brands: {len(DOMAINS)}")
    print("wrote: ca/mock-domains.txt, proxy/mocks.caddy, sites/webmock/aliases.txt")
    print("\nDNS aliases for the `proxy` service in compose.net.yml (already applied):")
    print(aliases)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
